# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "lucid64"

  # set up cpu exec cap so that Virtualbox doesn't kill my notebook
  # feel free to change memory_size and cpu_execution_cap based on your HW
  config.vm.customize do |vm|
  	vm.memory_size = 256
  	vm.name = "meetup.uy demo box"
  	vm.cpu_execution_cap = 50
  end
 
  config.vm.share_folder "packages", "/media/packages", "/Users/fernandoipar/vagrant_meetup/packages/", :create=>true

  # puppet provisioner
  config.vm.provision :puppet do |config_puppet|
    config_puppet.pp_path = "/tmp/vagrant-puppet"
    config_puppet.manifests_path = "manifests"
    config_puppet.manifest_file = "site.pp"
    config_puppet.options = "--verbose"
  end

#  config.vm.provision :shell, :path => "provisioner.sh"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/lucid64.box"

end
